fix run on MacOS
vlingo-net/vlingo-net-http pull request #6
Opened 2020-12-26 21:24 UTC by hellxcz

https://github.com/vlingo-net/vlingo-net-http/issues/5

2020-12-26 21:42 UTC, tjaskula requested changes
Thanks for the contribution.
My gut feeling is that it's not dependent on Mac but maybe on your local culture.

Could you provide a Unit Test that proves the not working behavior was fixed ?

2020-12-26 21:42 UTC, tjaskula commented on src/Vlingo.Http.Tests/Resource/ResourceTestFixtures.cs
> +        protected readonly string NewLineDelimiter = "\n";
This is exactly the same as inlined `\n` before

2020-12-26 21:42 UTC, tjaskula commented on src/Vlingo.Http/RequestParser.cs
> -                var lineBreak = _requestText.IndexOf("\n", _position, StringComparison.InvariantCultureIgnoreCase);
The invariant culture has to be there. It should not depend on the specific culture.

2020-12-26 21:42 UTC, tjaskula commented on src/Vlingo.Http/RequestParser.cs
> +                var lineBreak = _requestText.IndexOf(NewLineDelimiter, _position);
`IndexOf` supports both, string and char so maybe the difference is on your local culture and the fact that `StringComparison.InvariantCultureIgnoreCase` was used.

2020-12-27 21:19 UTC, hellxcz commented on src/Vlingo.Http/RequestParser.cs
> +        public static readonly char NewLineDelimiter = '\n';
here it is of type char.

2020-12-28 20:07 UTC, tjaskula commented
Thanks @hellxcz for valuable feedback. I just addressed it in https://github.com/vlingo-net/vlingo-net-http/compare/380816e16a69...7b2d9c6d7fe6.

2020-12-28 20:07 UTC, closed without merging